#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.13
# In conjunction with Tcl version 8.6
#    May 20, 2018 01:06:02 PM


import sys
import DB_operations_project as dbo

try:
    from Tkinter import *
except ImportError:
    from Tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import Tkinter.ttk as ttk
    py3 = True


def set_Tk_var():
    global title
    title = StringVar()
    global sub
    sub = StringVar()
    global auth
    auth = StringVar()

def close_window():
    #print('bookaddition_support.close_window')
    destroy_window()
    import employee_operations as e
    e.vp_start_gui()
    sys.stdout.flush()

def sub_book_details():
    #print('bookaddition_support.sub_book_details')
    t=title.get()
    s=sub.get()
    a=auth.get()
    dbo.add_book(t,s,a)
    sys.stdout.flush()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import bookaddition
    bookaddition.vp_start_gui()


