#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.13
# In conjunction with Tcl version 8.6
#    May 20, 2018 08:02:49 PM


import sys
import tkMessageBox as tkmsg
try:
    from Tkinter import *
except ImportError:
    from Tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import Tkinter.ttk as ttk
    py3 = True
def set_Tk_var():
    global book_id
    book_id = StringVar()
    global txt
    txt = StringVar()

def close():
    print('Deletion_search_support.close')
    destroy_window()
    import employee_operations as e
    e.vp_start_gui()
    sys.stdout.flush()


def delete_book():
    #print('Deletion_search_support.delete_book')
    id = book_id.get()
    import DB_operations_project as dbo
    dbo.delete_books(id)
    sys.stdout.flush()


def search_book():
    #print('Deletion_search_support.search_book')
    text=txt.get()
    import search_result
    search_result.vp_start_gui()
    search_result.Search_Result.__init__(text)

    sys.stdout.flush()


def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import Deletion_search
    Deletion_search.vp_start_gui()


