#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.13
# In conjunction with Tcl version 8.6
#    May 20, 2018 08:02:54 PM

import sys

try:
    from Tkinter import *
except ImportError:
    from Tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import Tkinter.ttk as ttk
    py3 = True

import Deletion_search_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    Deletion_search_support.set_Tk_var()
    top = Deletion_Search (root)
    Deletion_search_support.init(root, top)
    root.mainloop()

w = None
def create_Deletion_Search(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    Deletion_search_support.set_Tk_var()
    top = Deletion_Search (w)
    Deletion_search_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Deletion_Search():
    global w
    w.destroy()
    w = None


class Deletion_Search:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        font10 = "-family {Segoe UI Emoji} -size 10 -weight bold "  \
            "-slant roman -underline 0 -overstrike 0"
        font11 = "-family {Segoe UI} -size 11 -weight bold -slant "  \
            "roman -underline 0 -overstrike 0"
        font9 = "-family {Wide Latin} -size 10 -weight normal -slant "  \
            "roman -underline 0 -overstrike 0"

        top.geometry("600x433+650+150")
        top.title("Deletion/Search")
        top.configure(background="#97d2d8")



        self.Label1 = Label(top)
        self.Label1.place(relx=0.15, rely=0.05, height=30, width=440)
        self.Label1.configure(background="#97d2d8")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font=font9)
        self.Label1.configure(foreground="#4a5b9e")
        self.Label1.configure(text='''Delete/Search Book Here''')

        self.Label2 = Label(top)
        self.Label2.place(relx=0.05, rely=0.32, height=33, width=136)
        self.Label2.configure(background="#97d2d8")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(font=font10)
        self.Label2.configure(foreground="#3524d1")
        self.Label2.configure(text='''Enter Book Id''')

        self.Entry1 = Entry(top)
        self.Entry1.place(relx=0.3, rely=0.32,height=36, relwidth=0.41)
        self.Entry1.configure(background="white")
        self.Entry1.configure(disabledforeground="#a3a3a3")
        self.Entry1.configure(font="TkFixedFont")
        self.Entry1.configure(foreground="#000000")
        self.Entry1.configure(insertbackground="black")
        self.Entry1.configure(textvariable=Deletion_search_support.book_id)
        self.Entry1.configure(width=244)

        self.Button1 = Button(top)
        self.Button1.place(relx=0.77, rely=0.32, height=32, width=75)
        self.Button1.configure(activebackground="#d9d9d9")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#558ee5")
        self.Button1.configure(command=Deletion_search_support.delete_book)
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(foreground="#ffffff")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''Delete''')
        self.Button1.configure(width=75)

        self.Button2 = Button(top)
        self.Button2.place(relx=0.77, rely=0.55, height=32, width=77)
        self.Button2.configure(activebackground="#d9d9d9")
        self.Button2.configure(activeforeground="#000000")
        self.Button2.configure(background="#558ee5")
        self.Button2.configure(command=Deletion_search_support.search_book)
        self.Button2.configure(disabledforeground="#a3a3a3")
        self.Button2.configure(foreground="#ffffff")
        self.Button2.configure(highlightbackground="#d9d9d9")
        self.Button2.configure(highlightcolor="black")
        self.Button2.configure(pady="0")
        self.Button2.configure(text='''Search''')
        self.Button2.configure(width=77)

        self.Button3 = Button(top)
        self.Button3.place(relx=0.93, rely=0.0, height=42, width=43)
        self.Button3.configure(activebackground="#d9d9d9")
        self.Button3.configure(activeforeground="#000000")
        self.Button3.configure(background="#ffffff")
        self.Button3.configure(command=Deletion_search_support.close)
        self.Button3.configure(disabledforeground="#a3a3a3")
        self.Button3.configure(font=font11)
        self.Button3.configure(foreground="#ef1a30")
        self.Button3.configure(highlightbackground="#d9d9d9")
        self.Button3.configure(highlightcolor="black")
        self.Button3.configure(pady="0")
        self.Button3.configure(text='''x''')
        self.Button3.configure(width=43)

        self.Label3 = Label(top)
        self.Label3.place(relx=0.07, rely=0.55, height=33, width=102)
        self.Label3.configure(background="#97d2d8")
        self.Label3.configure(disabledforeground="#a3a3a3")
        self.Label3.configure(font=font10)
        self.Label3.configure(foreground="#3524d1")
        self.Label3.configure(text='''Enter Text''')

        self.Entry2 = Entry(top)
        self.Entry2.place(relx=0.3, rely=0.55,height=36, relwidth=0.41)
        self.Entry2.configure(background="white")
        self.Entry2.configure(disabledforeground="#a3a3a3")
        self.Entry2.configure(font="TkFixedFont")
        self.Entry2.configure(foreground="#000000")
        self.Entry2.configure(insertbackground="black")
        self.Entry2.configure(textvariable=Deletion_search_support.txt)
        self.Entry2.configure(width=244)






if __name__ == '__main__':
    vp_start_gui()



