#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.13
# In conjunction with Tcl version 8.6
#    May 18, 2018 06:35:00 PM


import sys

try:
    from Tkinter import *
except ImportError:
    from Tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import Tkinter.ttk as ttk
    py3 = True

def add_book_details():
    #print('employee_operations_support.add_book_details')
    destroy_window()
    import bookaddition
    bookaddition.vp_start_gui()
    sys.stdout.flush()


def delete_book():
    #print('employee_operations_support.delete_book')
    destroy_window()
    import Deletion_search as ds
    ds.vp_start_gui()
    sys.stdout.flush()


def issue_book():
    #print('employee_operations_support.issue_book')
    destroy_window()
    import issue
    issue.vp_start_gui()
    sys.stdout.flush()


def reg_new_emp():
    #print('employee_operations_support.reg_new_emp')
    import Registrationemployee as reg
    reg.vp_start_gui()
    sys.stdout.flush()

def search_book():
    #print('employee_operations_support.search_book')
    import Deletion_search
    Deletion_search.vp_start_gui()
    sys.stdout.flush()

def view_book_list():
    #print('employee_operations_support.view_book_list')
    import show_result
    show_result.vp_start_gui()
    sys.stdout.flush()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import employee_operations
    employee_operations.vp_start_gui()


