#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.13
# In conjunction with Tcl version 8.6
#    May 20, 2018 10:07:54 PM

import sys

try:
    from Tkinter import *
except ImportError:
    from Tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import Tkinter.ttk as ttk
    py3 = True

import issue_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    issue_support.set_Tk_var()
    top = issue_Book (root)
    issue_support.init(root, top)
    root.mainloop()

w = None
def create_issue_Book(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    issue_support.set_Tk_var()
    top = issue_Book (w)
    issue_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_issue_Book():
    global w
    w.destroy()
    w = None


class issue_Book:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 

        top.geometry("741x495+650+150")
        top.title("issue Book")
        top.configure(background="#d9d9d9")



        self.Canvas1 = Canvas(top)
        self.Canvas1.place(relx=0.08, rely=0.08, relheight=0.83, relwidth=0.83)
        self.Canvas1.configure(background="#babaff")
        self.Canvas1.configure(borderwidth="6")
        self.Canvas1.configure(insertbackground="black")
        self.Canvas1.configure(relief=RIDGE)
        self.Canvas1.configure(selectbackground="#c4c4c4")
        self.Canvas1.configure(selectforeground="black")
        self.Canvas1.configure(width=613)

        self.Label1 = Label(self.Canvas1)
        self.Label1.place(relx=0.16, rely=0.27, height=31, width=68)
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(relief=SUNKEN)
        self.Label1.configure(text='''Book Id''')

        self.Label2 = Label(self.Canvas1)
        self.Label2.place(relx=0.16, rely=0.44, height=31, width=73)
        self.Label2.configure(background="#d9d9d9")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(relief=SUNKEN)
        self.Label2.configure(text='''issuedto''')

        self.Label3 = Label(self.Canvas1)
        self.Label3.place(relx=0.16, rely=0.61, height=31, width=76)
        self.Label3.configure(background="#d9d9d9")
        self.Label3.configure(disabledforeground="#a3a3a3")
        self.Label3.configure(foreground="#000000")
        self.Label3.configure(relief=SUNKEN)
        self.Label3.configure(text='''issuedby''')

        self.Entry1 = Entry(self.Canvas1)
        self.Entry1.place(relx=0.41, rely=0.27,height=26, relwidth=0.4)
        self.Entry1.configure(background="white")
        self.Entry1.configure(disabledforeground="#a3a3a3")
        self.Entry1.configure(font="TkFixedFont")
        self.Entry1.configure(foreground="#000000")
        self.Entry1.configure(insertbackground="black")
        self.Entry1.configure(textvariable=issue_support.bookid)

        self.Entry2 = Entry(self.Canvas1)
        self.Entry2.place(relx=0.41, rely=0.44,height=26, relwidth=0.4)
        self.Entry2.configure(background="white")
        self.Entry2.configure(disabledforeground="#a3a3a3")
        self.Entry2.configure(font="TkFixedFont")
        self.Entry2.configure(foreground="#000000")
        self.Entry2.configure(insertbackground="black")
        self.Entry2.configure(textvariable=issue_support.issueto)

        self.Entry3 = Entry(self.Canvas1)
        self.Entry3.place(relx=0.41, rely=0.61,height=26, relwidth=0.4)
        self.Entry3.configure(background="white")
        self.Entry3.configure(disabledforeground="#a3a3a3")
        self.Entry3.configure(font="TkFixedFont")
        self.Entry3.configure(foreground="#000000")
        self.Entry3.configure(insertbackground="black")
        self.Entry3.configure(textvariable=issue_support.issueby)

        self.Button1 = Button(self.Canvas1)
        self.Button1.place(relx=0.33, rely=0.82, height=42, width=54)
        self.Button1.configure(activebackground="#d9d9d9")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#d9d9d9")
        self.Button1.configure(command=issue_support.isuue_bk)
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''issue''')

        self.Button2 = Button(self.Canvas1)
        self.Button2.place(relx=0.52, rely=0.82, height=42, width=55)
        self.Button2.configure(activebackground="#d9d9d9")
        self.Button2.configure(activeforeground="#000000")
        self.Button2.configure(background="#d9d9d9")
        self.Button2.configure(command=issue_support.close)
        self.Button2.configure(disabledforeground="#a3a3a3")
        self.Button2.configure(foreground="#000000")
        self.Button2.configure(highlightbackground="#d9d9d9")
        self.Button2.configure(highlightcolor="black")
        self.Button2.configure(pady="0")
        self.Button2.configure(text='''close''')






if __name__ == '__main__':
    vp_start_gui()



