#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.13
# In conjunction with Tcl version 8.6
#    May 18, 2018 07:18:17 PM

import sys

try:
    from Tkinter import *
except ImportError:
    from Tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import Tkinter.ttk as ttk
    py3 = True

import login_library_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    login_library_support.set_Tk_var()
    top = Login_page (root)
    login_library_support.init(root, top)
    root.mainloop()

w = None
def create_Login_page(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    login_library_support.set_Tk_var()
    top = Login_page (w)
    login_library_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Login_page():
    global w
    w.destroy()
    w = None


class Login_page:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        font9 = "-family SimSun -size 14 -weight bold -slant roman "  \
            "-underline 0 -overstrike 0"

        top.geometry("701x464+650+150")
        top.title("Login page")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")



        self.Canvas1 = Canvas(top)
        self.Canvas1.place(relx=0.09, rely=0.28, relheight=0.61, relwidth=0.82)
        self.Canvas1.configure(background="#d9d9d9")
        self.Canvas1.configure(borderwidth="6")
        self.Canvas1.configure(closeenough="3.0")
        self.Canvas1.configure(highlightbackground="#5b7def")
        self.Canvas1.configure(highlightcolor="#3f3f3f")
        self.Canvas1.configure(insertbackground="black")
        self.Canvas1.configure(relief=RIDGE)
        self.Canvas1.configure(selectbackground="#c4c4c4")
        self.Canvas1.configure(selectforeground="black")
        self.Canvas1.configure(width=573)

        self.Label2 = Label(self.Canvas1)
        self.Label2.place(relx=0.14, rely=0.18, height=31, width=93)
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(activeforeground="black")
        self.Label2.configure(background="#d9d9d9")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(foreground="#171791")
        self.Label2.configure(highlightbackground="#d9d9d9")
        self.Label2.configure(highlightcolor="black")
        self.Label2.configure(text='''User Id''')

        self.Label3 = Label(self.Canvas1)
        self.Label3.place(relx=0.14, rely=0.42, height=31, width=82)
        self.Label3.configure(activebackground="#f9f9f9")
        self.Label3.configure(activeforeground="black")
        self.Label3.configure(background="#d9d9d9")
        self.Label3.configure(disabledforeground="#a3a3a3")
        self.Label3.configure(foreground="#171791")
        self.Label3.configure(highlightbackground="#d9d9d9")
        self.Label3.configure(highlightcolor="black")
        self.Label3.configure(text='''Password''')

        self.uname = Entry(self.Canvas1)
        self.uname.place(relx=0.38, rely=0.18,height=36, relwidth=0.46)
        self.uname.configure(background="white")
        self.uname.configure(disabledforeground="#a3a3a3")
        self.uname.configure(font="TkFixedFont")
        self.uname.configure(foreground="#000000")
        self.uname.configure(highlightbackground="#d9d9d9")
        self.uname.configure(highlightcolor="black")
        self.uname.configure(insertbackground="black")
        self.uname.configure(selectbackground="#c4c4c4")
        self.uname.configure(selectforeground="black")
        self.uname.configure(textvariable=login_library_support.uname)

        self.pswd = Entry(self.Canvas1)
        self.pswd.place(relx=0.38, rely=0.42,height=36, relwidth=0.46,)
        self.pswd.configure(background="white")
        self.pswd.configure(disabledforeground="#a3a3a3")
        self.pswd.configure(font="TkFixedFont")
        self.pswd.configure(foreground="#000000")
        self.pswd.configure(highlightbackground="#d9d9d9")
        self.pswd.configure(highlightcolor="black")
        self.pswd.configure(insertbackground="black")
        self.pswd.configure(selectbackground="#c4c4c4")
        self.pswd.configure(selectforeground="black")
        self.pswd.configure(show="*")
        self.pswd.configure(textvariable=login_library_support.pswd)

        self.Button1 = Button(self.Canvas1)
        self.Button1.place(relx=0.14, rely=0.74, height=42, width=79)
        self.Button1.configure(activebackground="#d9d9d9")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#ffffff")
        self.Button1.configure(command=login_library_support.loginFunction)
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(foreground="#06d15e")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''Login''')

        self.Button2 = Button(self.Canvas1)
        self.Button2.place(relx=0.44, rely=0.74, height=42, width=79)
        self.Button2.configure(activebackground="#d9d9d9")
        self.Button2.configure(activeforeground="#000000")
        self.Button2.configure(background="#d7e0f4")
        self.Button2.configure(command=login_library_support.registerbutton)
        self.Button2.configure(disabledforeground="#a3a3a3")
        self.Button2.configure(foreground="#1b4b9e")
        self.Button2.configure(highlightbackground="#d9d9d9")
        self.Button2.configure(highlightcolor="black")
        self.Button2.configure(pady="0")
        self.Button2.configure(text='''Register''')

        self.Label1 = Label(top)
        self.Label1.place(relx=0.09, rely=0.11, height=54, width=566)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(background="#d7e0f4")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font=font9)
        self.Label1.configure(foreground="#171791")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(relief=SUNKEN)
        self.Label1.configure(text='''Welcome User!!''')

        self.Button3 = Button(top)
        self.Button3.place(relx=0.67, rely=0.73, height=42, width=68)
        self.Button3.configure(activebackground="#d9d9d9")
        self.Button3.configure(activeforeground="#000000")
        self.Button3.configure(background="#ffffff")
        self.Button3.configure(command=login_library_support.closewindow)
        self.Button3.configure(disabledforeground="#a3a3a3")
        self.Button3.configure(foreground="#ef2c0e")
        self.Button3.configure(highlightbackground="#d9d9d9")
        self.Button3.configure(highlightcolor="black")
        self.Button3.configure(pady="0")
        self.Button3.configure(text='''Close''')






if __name__ == '__main__':
    vp_start_gui()



