#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.13
# In conjunction with Tcl version 8.6
#    May 18, 2018 06:42:42 PM
#    May 18, 2018 09:51:58 PM


import sys
import DB_operations_project as dbo
import tkMessageBox as tkmsg

try:
    from Tkinter import *
except ImportError:
    from Tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import Tkinter.ttk as ttk
    py3 = True


def set_Tk_var():
    global ename
    ename = StringVar()
    global eid
    eid = StringVar()
    global emp_dept
    emp_dept = StringVar()
    global doj
    doj = StringVar()
    global sal
    sal = StringVar()
    global password
    password = StringVar()


def back_gotologin():
    #print('Registrationemployee_support.back_gotologin')
    destroy_window()
    import employee_operations
    employee_operations.vp_start_gui()
    sys.stdout.flush()


def submit_emp_data():
    #print('Registrationemployee_support.submit_emp_data')
    nm = ename.get()
    id1 = eid.get()
    dep = emp_dept.get()
    date = doj.get()
    s = sal.get()
    p= password.get()
    dbo.register_newemployee(nm, id1, dep, date, s,p)
    sys.stdout.flush()


def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top


def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None


if __name__ == '__main__':
    import Registrationemployee
    Registrationemployee.vp_start_gui()





