#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.13
# In conjunction with Tcl version 8.6
#    May 18, 2018 09:52:13 PM

import sys

try:
    from Tkinter import *
except ImportError:
    from Tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import Tkinter.ttk as ttk
    py3 = True

import Registrationemployee_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    Registrationemployee_support.set_Tk_var()
    top = SignUp_Register_Employee_ (root)
    Registrationemployee_support.init(root, top)
    root.mainloop()

w = None
def create_SignUp_Register_Employee_(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    Registrationemployee_support.set_Tk_var()
    top = SignUp_Register_Employee_ (w)
    Registrationemployee_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_SignUp_Register_Employee_():
    global w
    w.destroy()
    w = None


class SignUp_Register_Employee_:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        font10 = "-family {Segoe UI} -size 9 -weight bold -slant roman"  \
            " -underline 0 -overstrike 0"
        font9 = "-family {Showcard Gothic} -size 13 -weight normal "  \
            "-slant roman -underline 0 -overstrike 0"

        top.geometry("655x846+704+37")
        top.title("SignUp/Register(Employee)")
        top.configure(background="#b0ffb0")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")



        self.menubar = Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)



        self.Label1 = Label(top)
        self.Label1.place(relx=0.18, rely=0.02, height=31, width=397)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(background="#daffb5")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font=font9)
        self.Label1.configure(foreground="#239165")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''Registeration   Form''')

        self.Canvas1 = Canvas(top)
        self.Canvas1.place(relx=0.08, rely=0.09, relheight=0.83, relwidth=0.84)
        self.Canvas1.configure(background="#f4fff2")
        self.Canvas1.configure(borderwidth="4")
        self.Canvas1.configure(highlightbackground="#21961c")
        self.Canvas1.configure(highlightcolor="black")
        self.Canvas1.configure(insertbackground="black")
        self.Canvas1.configure(relief=RIDGE)
        self.Canvas1.configure(selectbackground="#c4c4c4")
        self.Canvas1.configure(selectforeground="black")
        self.Canvas1.configure(width=553)

        self.Label2 = Label(self.Canvas1)
        self.Label2.place(relx=0.14, rely=0.11, height=31, width=56)
        self.Label2.configure(activebackground="#f4fff2")
        self.Label2.configure(activeforeground="black")
        self.Label2.configure(background="#f4fff2")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(font=font10)
        self.Label2.configure(foreground="#1d6815")
        self.Label2.configure(highlightbackground="#d9d9d9")
        self.Label2.configure(highlightcolor="black")
        self.Label2.configure(text='''Name''')

        self.Label3 = Label(self.Canvas1)
        self.Label3.place(relx=0.14, rely=0.23, height=31, width=67)
        self.Label3.configure(activebackground="#f9f9f9")
        self.Label3.configure(activeforeground="black")
        self.Label3.configure(background="#f4fff2")
        self.Label3.configure(disabledforeground="#a3a3a3")
        self.Label3.configure(font=font10)
        self.Label3.configure(foreground="#1d6815")
        self.Label3.configure(highlightbackground="#d9d9d9")
        self.Label3.configure(highlightcolor="black")
        self.Label3.configure(text='''Emp ID''')

        self.Label4 = Label(self.Canvas1)
        self.Label4.place(relx=0.14, rely=0.34, height=31, width=108)
        self.Label4.configure(activebackground="#f9f9f9")
        self.Label4.configure(activeforeground="black")
        self.Label4.configure(background="#f4fff2")
        self.Label4.configure(disabledforeground="#a3a3a3")
        self.Label4.configure(font=font10)
        self.Label4.configure(foreground="#1d6815")
        self.Label4.configure(highlightbackground="#d9d9d9")
        self.Label4.configure(highlightcolor="black")
        self.Label4.configure(text='''Department''')

        self.Label5 = Label(self.Canvas1)
        self.Label5.place(relx=0.14, rely=0.46, height=31, width=41)
        self.Label5.configure(activebackground="#f9f9f9")
        self.Label5.configure(activeforeground="black")
        self.Label5.configure(background="#f4fff2")
        self.Label5.configure(disabledforeground="#a3a3a3")
        self.Label5.configure(font=font10)
        self.Label5.configure(foreground="#1d6815")
        self.Label5.configure(highlightbackground="#d9d9d9")
        self.Label5.configure(highlightcolor="black")
        self.Label5.configure(text='''DOJ''')

        self.Label6 = Label(self.Canvas1)
        self.Label6.place(relx=0.14, rely=0.57, height=31, width=58)
        self.Label6.configure(activebackground="#f9f9f9")
        self.Label6.configure(activeforeground="black")
        self.Label6.configure(background="#f4fff2")
        self.Label6.configure(disabledforeground="#a3a3a3")
        self.Label6.configure(font=font10)
        self.Label6.configure(foreground="#1d6815")
        self.Label6.configure(highlightbackground="#d9d9d9")
        self.Label6.configure(highlightcolor="black")
        self.Label6.configure(text='''Salary''')

        self.Label_pass = Label(self.Canvas1)
        self.Label_pass.place(relx=0.14, rely=0.66, height=31, width=58)
        self.Label_pass.configure(activebackground="#f9f9f9")
        self.Label_pass.configure(activeforeground="black")
        self.Label_pass.configure(background="#f4fff2")
        self.Label_pass.configure(disabledforeground="#a3a3a3")
        self.Label_pass.configure(font=font10)
        self.Label_pass.configure(foreground="#1d6815")
        self.Label_pass.configure(highlightbackground="#d9d9d9")
        self.Label_pass.configure(highlightcolor="black")
        self.Label_pass.configure(text='''password''')

        self.name = Entry(self.Canvas1)
        self.name.place(relx=0.42, rely=0.11,height=36, relwidth=0.44)
        self.name.configure(background="white")
        self.name.configure(disabledforeground="#a3a3a3")
        self.name.configure(font="TkFixedFont")
        self.name.configure(foreground="#000000")
        self.name.configure(highlightbackground="#d9d9d9")
        self.name.configure(highlightcolor="black")
        self.name.configure(insertbackground="black")
        self.name.configure(selectbackground="#c4c4c4")
        self.name.configure(selectforeground="black")
        self.name.configure(textvariable=Registrationemployee_support.ename)

        self.Empid = Entry(self.Canvas1)
        self.Empid.place(relx=0.42, rely=0.23,height=36, relwidth=0.44)
        self.Empid.configure(background="white")
        self.Empid.configure(disabledforeground="#a3a3a3")
        self.Empid.configure(font="TkFixedFont")
        self.Empid.configure(foreground="#000000")
        self.Empid.configure(highlightbackground="#d9d9d9")
        self.Empid.configure(highlightcolor="black")
        self.Empid.configure(insertbackground="black")
        self.Empid.configure(selectbackground="#c4c4c4")
        self.Empid.configure(selectforeground="black")
        self.Empid.configure(textvariable=Registrationemployee_support.eid)

        self.dept_emp = Entry(self.Canvas1)
        self.dept_emp.place(relx=0.42, rely=0.34,height=36, relwidth=0.44)
        self.dept_emp.configure(background="white")
        self.dept_emp.configure(disabledforeground="#a3a3a3")
        self.dept_emp.configure(font="TkFixedFont")
        self.dept_emp.configure(foreground="#000000")
        self.dept_emp.configure(highlightbackground="#d9d9d9")
        self.dept_emp.configure(highlightcolor="black")
        self.dept_emp.configure(insertbackground="black")
        self.dept_emp.configure(selectbackground="#c4c4c4")
        self.dept_emp.configure(selectforeground="black")
        self.dept_emp.configure(textvariable=Registrationemployee_support.emp_dept)

        self.doj = Entry(self.Canvas1)
        self.doj.place(relx=0.42, rely=0.44,height=36, relwidth=0.44)
        self.doj.configure(background="white")
        self.doj.configure(disabledforeground="#a3a3a3")
        self.doj.configure(font="TkFixedFont")
        self.doj.configure(foreground="#000000")
        self.doj.configure(highlightbackground="#d9d9d9")
        self.doj.configure(highlightcolor="black")
        self.doj.configure(insertbackground="black")
        self.doj.configure(selectbackground="#c4c4c4")
        self.doj.configure(selectforeground="black")
        self.doj.configure(textvariable=Registrationemployee_support.doj)

        self.sal = Entry(self.Canvas1)
        self.sal.place(relx=0.42, rely=0.57,height=36, relwidth=0.44)
        self.sal.configure(background="white")
        self.sal.configure(disabledforeground="#a3a3a3")
        self.sal.configure(font="TkFixedFont")
        self.sal.configure(foreground="#000000")
        self.sal.configure(highlightbackground="#d9d9d9")
        self.sal.configure(highlightcolor="black")
        self.sal.configure(insertbackground="black")
        self.sal.configure(selectbackground="#c4c4c4")
        self.sal.configure(selectforeground="black")
        self.sal.configure(textvariable=Registrationemployee_support.sal)

        self.password = Entry(self.Canvas1)
        self.password.place(relx=0.42, rely=0.66, height=36, relwidth=0.44)
        self.password.configure(background="white")
        self.password.configure(disabledforeground="#a3a3a3")
        self.password.configure(font="TkFixedFont")
        self.password.configure(foreground="#000000")
        self.password.configure(highlightbackground="#d9d9d9")
        self.password.configure(highlightcolor="black")
        self.password.configure(insertbackground="black")
        self.password.configure(selectbackground="#c4c4c4")
        self.password.configure(selectforeground="black")
        self.password.configure(show="*")
        self.password.configure(textvariable=Registrationemployee_support.password)

        self.Button1 = Button(self.Canvas1)
        self.Button1.place(relx=0.25, rely=0.81, height=42, width=102)
        self.Button1.configure(activebackground="#d9d9d9")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#35875b")
        self.Button1.configure(borderwidth="4")
        self.Button1.configure(command=Registrationemployee_support.submit_emp_data)
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(foreground="#fafffe")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''Submit''')

        self.Button2 = Button(self.Canvas1)
        self.Button2.place(relx=0.52, rely=0.81, height=42, width=98)
        self.Button2.configure(activebackground="#d9d9d9")
        self.Button2.configure(activeforeground="#000000")
        self.Button2.configure(background="#35875b")
        self.Button2.configure(borderwidth="4")
        self.Button2.configure(command=Registrationemployee_support.back_gotologin)
        self.Button2.configure(disabledforeground="#a3a3a3")
        self.Button2.configure(foreground="#defffc")
        self.Button2.configure(highlightbackground="#d9d9d9")
        self.Button2.configure(highlightcolor="black")
        self.Button2.configure(pady="0")
        self.Button2.configure(text='''Back''')


if __name__ == '__main__':
    vp_start_gui()



