#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.13
# In conjunction with Tcl version 8.6
#    May 18, 2018 10:46:49 PM

import sys

try:
    from Tkinter import *
except ImportError:
    from Tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import Tkinter.ttk as ttk
    py3 = True

import RegistrationStudent_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    RegistrationStudent_support.set_Tk_var()
    top = Registration_form_Students_ (root)
    RegistrationStudent_support.init(root, top)
    root.mainloop()

w = None
def create_Registration_form_Students_(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    RegistrationStudent_support.set_Tk_var()
    top = Registration_form_Students_ (w)
    RegistrationStudent_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Registration_form_Students_():
    global w
    w.destroy()
    w = None


class Registration_form_Students_:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        font10 = "-family {Segoe UI Black} -size 11 -weight bold "  \
            "-slant roman -underline 0 -overstrike 0"
        font9 = "-family {Segoe UI} -size 9 -weight bold -slant roman "  \
            "-underline 0 -overstrike 0"

        top.geometry("606x711+650+150")
        top.title("Registration form(Students)")
        top.configure(background="#fff8c9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")



        self.Label1 = Label(top)
        self.Label1.place(relx=0.31, rely=0.03, height=36, width=215)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(background="#fcf4a9")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font=font10)
        self.Label1.configure(foreground="#b5781d")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''Registeration Form''')

        self.Label2 = Label(top)
        self.Label2.place(relx=0.13, rely=0.15, height=31, width=128)
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(activeforeground="black")
        self.Label2.configure(background="#fff8c9")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(font=font9)
        self.Label2.configure(foreground="#845d22")
        self.Label2.configure(highlightbackground="#d9d9d9")
        self.Label2.configure(highlightcolor="black")
        self.Label2.configure(text='''Student Name''')

        self.Label3 = Label(top)
        self.Label3.place(relx=0.13, rely=0.27, height=31, width=69)
        self.Label3.configure(activebackground="#f9f9f9")
        self.Label3.configure(activeforeground="black")
        self.Label3.configure(background="#fff8c9")
        self.Label3.configure(disabledforeground="#a3a3a3")
        self.Label3.configure(font=font9)
        self.Label3.configure(foreground="#845d22")
        self.Label3.configure(highlightbackground="#d9d9d9")
        self.Label3.configure(highlightcolor="black")
        self.Label3.configure(text='''Roll No''')

        self.Label4 = Label(top)
        self.Label4.place(relx=0.13, rely=0.38, height=31, width=108)
        self.Label4.configure(activebackground="#f9f9f9")
        self.Label4.configure(activeforeground="black")
        self.Label4.configure(background="#fff8c9")
        self.Label4.configure(disabledforeground="#a3a3a3")
        self.Label4.configure(font=font9)
        self.Label4.configure(foreground="#845d22")
        self.Label4.configure(highlightbackground="#d9d9d9")
        self.Label4.configure(highlightcolor="black")
        self.Label4.configure(text='''Department''')

        self.Label5 = Label(top)
        self.Label5.place(relx=0.13, rely=0.51, height=31, width=84)
        self.Label5.configure(activebackground="#f9f9f9")
        self.Label5.configure(activeforeground="black")
        self.Label5.configure(background="#fff8c9")
        self.Label5.configure(disabledforeground="#a3a3a3")
        self.Label5.configure(font=font9)
        self.Label5.configure(foreground="#845d22")
        self.Label5.configure(highlightbackground="#d9d9d9")
        self.Label5.configure(highlightcolor="black")
        self.Label5.configure(text='''Semester''')

        self.Label6 = Label(top)
        self.Label6.place(relx=0.13, rely=0.63, height=31, width=55)
        self.Label6.configure(activebackground="#f9f9f9")
        self.Label6.configure(activeforeground="black")
        self.Label6.configure(background="#fff8c9")
        self.Label6.configure(disabledforeground="#a3a3a3")
        self.Label6.configure(font=font9)
        self.Label6.configure(foreground="#845d22")
        self.Label6.configure(highlightbackground="#d9d9d9")
        self.Label6.configure(highlightcolor="black")
        self.Label6.configure(text='''Batch''')

        self.names = Entry(top)
        self.names.place(relx=0.38, rely=0.15,height=26, relwidth=0.4)
        self.names.configure(background="white")
        self.names.configure(disabledforeground="#a3a3a3")
        self.names.configure(font="TkFixedFont")
        self.names.configure(foreground="#000000")
        self.names.configure(highlightbackground="#d9d9d9")
        self.names.configure(highlightcolor="black")
        self.names.configure(insertbackground="black")
        self.names.configure(selectbackground="#c4c4c4")
        self.names.configure(selectforeground="black")
        self.names.configure(textvariable=RegistrationStudent_support.names)

        self.roll = Entry(top)
        self.roll.place(relx=0.38, rely=0.27,height=26, relwidth=0.4)
        self.roll.configure(background="white")
        self.roll.configure(disabledforeground="#a3a3a3")
        self.roll.configure(font="TkFixedFont")
        self.roll.configure(foreground="#000000")
        self.roll.configure(highlightbackground="#d9d9d9")
        self.roll.configure(highlightcolor="black")
        self.roll.configure(insertbackground="black")
        self.roll.configure(selectbackground="#c4c4c4")
        self.roll.configure(selectforeground="black")
        self.roll.configure(textvariable=RegistrationStudent_support.roll)

        self.depart = Entry(top)
        self.depart.place(relx=0.38, rely=0.39,height=26, relwidth=0.4)
        self.depart.configure(background="white")
        self.depart.configure(disabledforeground="#a3a3a3")
        self.depart.configure(font="TkFixedFont")
        self.depart.configure(foreground="#000000")
        self.depart.configure(highlightbackground="#d9d9d9")
        self.depart.configure(highlightcolor="black")
        self.depart.configure(insertbackground="black")
        self.depart.configure(selectbackground="#c4c4c4")
        self.depart.configure(selectforeground="black")
        self.depart.configure(textvariable=RegistrationStudent_support.depart)

        self.sem = Entry(top)
        self.sem.place(relx=0.38, rely=0.51,height=26, relwidth=0.4)
        self.sem.configure(background="white")
        self.sem.configure(disabledforeground="#a3a3a3")
        self.sem.configure(font="TkFixedFont")
        self.sem.configure(foreground="#000000")
        self.sem.configure(highlightbackground="#d9d9d9")
        self.sem.configure(highlightcolor="black")
        self.sem.configure(insertbackground="black")
        self.sem.configure(selectbackground="#c4c4c4")
        self.sem.configure(selectforeground="black")
        self.sem.configure(textvariable=RegistrationStudent_support.sem)

        self.Label_password = Label(top)
        self.Label_password.place(relx=0.13, rely=0.75, height=31, width=128)
        self.Label_password.configure(activebackground="#f9f9f9")
        self.Label_password.configure(activeforeground="black")
        self.Label_password.configure(background="#fff8c9")
        self.Label_password.configure(disabledforeground="#a3a3a3")
        self.Label_password.configure(font=font9)
        self.Label_password.configure(foreground="#845d22")
        self.Label_password.configure(highlightbackground="#d9d9d9")
        self.Label_password.configure(highlightcolor="black")
        self.Label_password.configure(text='''Password''')

        self.batch = Entry(top)
        self.batch.place(relx=0.38, rely=0.63,height=26, relwidth=0.4)
        self.batch.configure(background="white")
        self.batch.configure(disabledforeground="#a3a3a3")
        self.batch.configure(font="TkFixedFont")
        self.batch.configure(foreground="#000000")
        self.batch.configure(highlightbackground="#d9d9d9")
        self.batch.configure(highlightcolor="black")
        self.batch.configure(insertbackground="black")
        self.batch.configure(selectbackground="#c4c4c4")
        self.batch.configure(selectforeground="black")
        self.batch.configure(textvariable=RegistrationStudent_support.batch)

        self.password = Entry(top)
        self.password.place(relx=0.38, rely=0.75, height=26, relwidth=0.4)
        self.password.configure(background="white")
        self.password.configure(disabledforeground="#a3a3a3")
        self.password.configure(font="TkFixedFont")
        self.password.configure(foreground="#000000")
        self.password.configure(highlightbackground="#d9d9d9")
        self.password.configure(highlightcolor="black")
        self.password.configure(insertbackground="black")
        self.password.configure(selectbackground="#c4c4c4")
        self.password.configure(selectforeground="black")
        self.password.configure(show="*")
        self.password.configure(textvariable=RegistrationStudent_support.password)
        
        

        self.Button1 = Button(top)
        self.Button1.place(relx=0.28, rely=0.86, height=42, width=102)
        self.Button1.configure(activebackground="#d9d9d9")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#d8a42b")
        self.Button1.configure(command=RegistrationStudent_support.submit_stu_data)
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''Submit''')


        self.Button2 = Button(top)
        self.Button2.place(relx=0.56, rely=0.86, height=42, width=102)
        self.Button2.configure(activebackground="#d9d9d9")
        self.Button2.configure(activeforeground="#000000")
        self.Button2.configure(anchor=N)
        self.Button2.configure(background="#d8a42b")
        self.Button2.configure(command=RegistrationStudent_support.closeRegWindow)
        self.Button2.configure(disabledforeground="#a3a3a3")
        self.Button2.configure(foreground="#000000")
        self.Button2.configure(highlightbackground="#d9d9d9")
        self.Button2.configure(highlightcolor="black")
        self.Button2.configure(pady="0")
        self.Button2.configure(text='''Close''')






'''if __name__ == '__main__':
    vp_start_gui()'''



