#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.13
# In conjunction with Tcl version 8.6
#    May 18, 2018 09:48:17 AM

import sys

try:
    from Tkinter import *
except ImportError:
    from Tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import student_operations_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    top = Student_Operations_user_ (root)
    student_operations_support.init(root, top)
    root.mainloop()

w = None
def create_Student_Operations_user_(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    top = Student_Operations_user_ (w)
    student_operations_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Student_Operations_user_():
    global w
    w.destroy()
    w = None


class Student_Operations_user_:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        font10 = "-family {Segoe UI} -size 9 -weight bold -slant roman"  \
            " -underline 0 -overstrike 0"
        font11 = "-family {Segoe UI Symbol} -size 9 -weight normal "  \
            "-slant roman -underline 0 -overstrike 0"
        font9 = "-family {Segoe UI Historic} -size 9 -weight normal "  \
            "-slant roman -underline 0 -overstrike 0"

        top.geometry("696x492+650+150")
        top.title("Student_Operations(user)")
        top.configure(background="#bde0ff")



        self.Labelframe1 = LabelFrame(top)
        self.Labelframe1.place(relx=0.09, rely=0.06, relheight=0.84
                , relwidth=0.82)
        self.Labelframe1.configure(borderwidth="6")
        self.Labelframe1.configure(font=font9)
        self.Labelframe1.configure(foreground="black")
        self.Labelframe1.configure(relief=FLAT)
        self.Labelframe1.configure(text='''What operation do you want to perform?''')
        self.Labelframe1.configure(background="#f7f7f7")
        self.Labelframe1.configure(width=570)

        self.Button1 = Button(self.Labelframe1)
        self.Button1.place(relx=0.6, rely=0.8, height=42, width=87, y=-20)
        self.Button1.configure(activebackground="#d9d9d9")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#ffffff")
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(font=font10)
        self.Button1.configure(foreground="#139b3c")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''Register''')

        self.Label1 = Label(self.Labelframe1)
        self.Label1.place(relx=0.07, rely=0.24, height=41, width=170, y=-20)
        self.Label1.configure(background="#f7f7f7")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(foreground="#2a3bdb")
        self.Label1.configure(relief=SUNKEN)
        self.Label1.configure(text='''View Book List''')
        self.Label1.configure(width=170)

        self.Label2 = Label(self.Labelframe1)
        self.Label2.place(relx=0.07, rely=0.43, height=41, width=179, y=-20)
        self.Label2.configure(background="#f7f7f7")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(foreground="#2a3bdb")
        self.Label2.configure(relief=SUNKEN)
        self.Label2.configure(text='''Search a book''')
        self.Label2.configure(width=179)

        self.view = Button(self.Labelframe1)
        self.view.place(relx=0.75, rely=0.24, height=42, width=72, y=-20)
        self.view.configure(activebackground="#d9d9d9")
        self.view.configure(activeforeground="#000000")
        self.view.configure(background="#d3cfff")
        self.view.configure(borderwidth="4")
        self.view.configure(command=student_operations_support.view_book_List)
        self.view.configure(disabledforeground="#a3a3a3")
        self.view.configure(foreground="#000000")
        self.view.configure(highlightbackground="#d9d9d9")
        self.view.configure(highlightcolor="black")
        self.view.configure(pady="0")
        self.view.configure(text='''View''')
        self.view.configure(width=72)

        self.search = Button(self.Labelframe1)
        self.search.place(relx=0.75, rely=0.43, height=42, width=77, y=-20)
        self.search.configure(activebackground="#d9d9d9")
        self.search.configure(activeforeground="#000000")
        self.search.configure(background="#d3cfff")
        self.search.configure(borderwidth="4")
        self.search.configure(command=student_operations_support.search_book)
        self.search.configure(disabledforeground="#a3a3a3")
        self.search.configure(foreground="#000000")
        self.search.configure(highlightbackground="#d9d9d9")
        self.search.configure(highlightcolor="black")
        self.search.configure(pady="0")
        self.search.configure(text='''Search''')
        self.search.configure(width=77)

        self.Label3 = Label(self.Labelframe1)
        self.Label3.place(relx=0.14, rely=0.8, height=41, width=247, y=-20)
        self.Label3.configure(background="#e0e0e0")
        self.Label3.configure(disabledforeground="#a3a3a3")
        self.Label3.configure(font=font11)
        self.Label3.configure(foreground="#3d46c4")
        self.Label3.configure(text='''New user?? ->''')
        self.Label3.configure(width=247)



if __name__ == '__main__':
    vp_start_gui()



