#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.13
# In conjunction with Tcl version 8.6
#    May 18, 2018 09:48:11 AM


import sys
import DB_operations_project as dbo
try:
    from Tkinter import *
except ImportError:
    from Tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import Tkinter.ttk as ttk
    py3 = True


def search_book():
    #print('student_operations_support.search_book')
    destroy_window()
    import Deletion_search
    Deletion_search.vp_start_gui()
    sys.stdout.flush()

def view_book_List():
    #print('student_operations_support.view_book_List')
    import show_result
    show_result.vp_start_gui()
    sys.stdout.flush()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import student_operations
    student_operations.vp_start_gui()


